Ext.apply(
  Ext.ux.UploadDialog.Dialog.prototype.i18n,
  {
    title: '文件上传对话框',
    state_col_title: '状态',
    state_col_width: 70,
    filename_col_title: '文件',
    filename_col_width: 230,
    note_col_title: '结果',
    note_col_width: 150,
    add_btn_text: '添加',
    add_btn_tip: '添加文件到文件上传队列中.',
    remove_btn_text: '删除',
    remove_btn_tip: '从文件上传队列中删除文件.',
    reset_btn_text: '清空',
    reset_btn_tip: '清空文件上传队列.',
    upload_btn_start_text: '开始上传',
    upload_btn_stop_text: '停止上传',
    upload_btn_start_tip: '开始上传文件.',
    upload_btn_stop_tip: '停止上传文件.',
    close_btn_text: '关闭',
    close_btn_tip: '关闭文件上传对话框.',
    progress_waiting_text: '请稍等...',
    progress_uploading_text: '正在上传: 第{0}个文件， 共 {1} 个文件.',
    error_msgbox_title: '错误',
    permitted_extensions_join_str: ',',
    err_file_type_not_permitted: '不支持上传该类型的文件.<br/>请选择下列类型的文件：{1}',
    note_queued_to_upload: '排队等待上传.',
    note_processing: '正在上传...',
    note_upload_failed: '服务器错误.',
    note_upload_success: '上传成功.',
    note_upload_error: '上传错误.',
    note_aborted: '上传被中止.',
    note_canceled: '上传被取消.'
  }
);