	var DATATYPE_RAW = 0;
	var DATATYPE_MAX = 1;
	var DATATYPE_MIN = 2;
	var DATATYPE_AVG = 3;
	var DATATYPE_SNP = 4;

	var DATASTATUS_GOOD = 0;
	var DATASTATUS_BAD = 1;
	var DATASTATUS_MANUAL = 2;
	var DATASTATUS_TAGNOTEXIST = 3;
	var DATASTATUS_WRITESUCCESS = 4;
	var DATASTATUS_DATANOTEXIST = 5;